### ISSUE TITLE
Баг с кирилицей

### ISSUE THREAD

**Issue by zikkuratvk** [Joomline/jlnodoubles#3]
Описание и решение на JoomlaForum
http://joomlaforum.ru/index.php/topic,311192.msg1707815.html#msg1707815

**Comment by zikkuratvk** [comment]
11ae079

**Comment by zikkuratvk** [comment]
Разобрался баг есть действительно.

**Comment by Arkadiy-Sedelnikov** [comment]
8afc95d1cc46c462bf3562c8b4e8678269e8bc21
