### ISSUE TITLE
Сделать хотфикс "Бесконечная переадресация"

### ISSUE THREAD

**Issue by Septdir** [Joomline/jlnodoubles#7]
В общем не думаю что проблема неверного лайаута решиться так быстро как хочется, поэтому лучше будет сделать быстрый фикс.

Я бы сделал, но на то чтобы разобраться как работает jlnodoubles понадобиться время. А его как говориться не так много. 

Объяснять людям где вырезать кусок кода в ядре, или как-то там создавать пункты меню(я честно не знаю чем это может помочь) явно не лучшая затея

**Comment by Arkadiy-Sedelnikov** [comment]
Не могу добиться воспроизведения проблемы http://joomla.argens.ru/ Экспериментальный роутинг включил, но все в порядке. Не на чем исправлять.

**Comment by Septdir** [comment]
Там в PR есть описание как с тесотовго сайта воспроизвести проблему. 
Могу только сказать, что категория не должна быть главной.

А вообще могу дать бэкан одиного из своих тестовых сайтов. у меня на dev.joomlazen.com осталась эта поблема с пустым layput

**Comment by Arkadiy-Sedelnikov** [comment]
Давай. Не получается у меня добыть этот глюк.

**Comment by Septdir** [comment]
Скинул на мыло, правда не уверен будет ли баг с бесконечной переадрисацией. Но баг с лайаутам там точно есть. Еще как вариант можно сдлеать свой layout в шаблоне. может тоже вызвать баг ибо приходит не правильно.

Мини руководсво, да и пример тоже вроде был живой
https://septdir.ru/blog/web/joomla-com-contrent-override.html

**Comment by Arkadiy-Sedelnikov** [comment]
Бесконечную переадресацию я устрою, главное чтобы ссылка битая была. Спасибо, Игорь.

**Comment by Septdir** [comment]
Да нзч =)

**Comment by Arkadiy-Sedelnikov** [comment]
c52950466c5df3886c600ec600b3cc096357bf9b
